### PR TITLE
Export carousel type

### PR DESCRIPTION
**Pull request by lifedup**
Export EmblaCarousel type strictly for convenience.

### CODE REVIEW

**Comment by lifedup** [comment]
Sorry that was the wrong type.

**Comment by davidcetinkaya** [comment]
No worries @lifedup. Which type were you looking for? Maybe I could help?

**Comment by lifedup** [comment]
It was the user options type that was already being exported, I was moving too quickly and didn't see it.

**Comment by davidcetinkaya** [comment]
Thanks for the clarification. Enjoy and cheers!
David

**Pull request closed without merging**
